id: I81555355
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:18:36+00:00'
last_modified: '2022-06-07T14:14:12.697507+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29307
  title: གསུང་འབུམ། ངག་དབང་ཀུན་དགའ་བསོད་ནམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1BDB:
      image_group_id: I5209
      title: ''
      total_pages: 692
      order: 1
      base_file: 1BDB.txt
    A45A:
      image_group_id: I5210
      title: ''
      total_pages: 786
      order: 2
      base_file: A45A.txt
    '0007':
      image_group_id: I5211
      title: ''
      total_pages: 694
      order: 3
      base_file: 0007.txt
    4DC4:
      image_group_id: I5212
      title: ''
      total_pages: 778
      order: 4
      base_file: 4DC4.txt
    0BD5:
      image_group_id: I5213
      title: ''
      total_pages: 796
      order: 5
      base_file: 0BD5.txt
    CF90:
      image_group_id: I5214
      title: ''
      total_pages: 774
      order: 6
      base_file: CF90.txt
    ACBC:
      image_group_id: I5215
      title: ''
      total_pages: 852
      order: 7
      base_file: ACBC.txt
    CBEA:
      image_group_id: I5216
      title: ''
      total_pages: 834
      order: 8
      base_file: CBEA.txt
    '3903':
      image_group_id: I5217
      title: ''
      total_pages: 670
      order: 9
      base_file: 3903.txt
    860A:
      image_group_id: I5218
      title: ''
      total_pages: 732
      order: 10
      base_file: 860A.txt
    47BB:
      image_group_id: I5219
      title: ''
      total_pages: 798
      order: 11
      base_file: 47BB.txt
    DE41:
      image_group_id: I5220
      title: ''
      total_pages: 724
      order: 12
      base_file: DE41.txt
    472E:
      image_group_id: I5221
      title: ''
      total_pages: 738
      order: 13
      base_file: 472E.txt
    B14B:
      image_group_id: I5222
      title: ''
      total_pages: 720
      order: 14
      base_file: B14B.txt
    A43E:
      image_group_id: I5223
      title: ''
      total_pages: 836
      order: 15
      base_file: A43E.txt
    EA4E:
      image_group_id: I5224
      title: ''
      total_pages: 768
      order: 16
      base_file: EA4E.txt
    BE72:
      image_group_id: I5225
      title: ''
      total_pages: 662
      order: 17
      base_file: BE72.txt
    C4EE:
      image_group_id: I5226
      title: ''
      total_pages: 740
      order: 18
      base_file: C4EE.txt
    60F8:
      image_group_id: I5227
      title: ''
      total_pages: 726
      order: 19
      base_file: 60F8.txt
    DBA5:
      image_group_id: I5228
      title: ''
      total_pages: 716
      order: 20
      base_file: DBA5.txt
    4FF0:
      image_group_id: I5229
      title: ''
      total_pages: 700
      order: 21
      base_file: 4FF0.txt
    41A4:
      image_group_id: I5230
      title: ''
      total_pages: 736
      order: 22
      base_file: 41A4.txt
    '3731':
      image_group_id: I5231
      title: ''
      total_pages: 736
      order: 23
      base_file: 3731.txt
    778B:
      image_group_id: I5232
      title: ''
      total_pages: 734
      order: 24
      base_file: 778B.txt
    BAE4:
      image_group_id: I5233
      title: ''
      total_pages: 768
      order: 25
      base_file: BAE4.txt
    29BA:
      image_group_id: I5234
      title: ''
      total_pages: 744
      order: 26
      base_file: 29BA.txt
    D6A4:
      image_group_id: I5235
      title: ''
      total_pages: 754
      order: 27
      base_file: D6A4.txt
    '5515':
      image_group_id: I5236
      title: ''
      total_pages: 778
      order: 28
      base_file: 5515.txt
    0979:
      image_group_id: I5237
      title: ''
      total_pages: 240
      order: 29
      base_file: 0979.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
